### ISSUE TITLE
GitHub tagged releases are out of date

### ISSUE THREAD

**Issue by nick-iris** [usgs/xmax#49]
There hasn't been a tagged GitHub release since 2014. It would be nice to have a release to direct users to, since some users may not be familiar with using Git.

**Comment by jholland-usgs** [comment]
A new release v 2.1.0 was drafted.  Unfortunately, we aren't able to release the full binaries and the user will still need to build it themselves.

**Comment by nick-iris** [comment]
Thanks James!
